### PR TITLE
Add types spec

### PR DESCRIPTION
**Pull request by chabroA**
Add specification for types based on https://github.com/LedgerHQ/live-app-sdk/blob/main/docs/reference/modules.md

It looks like some types are not related to the specification (are more implementation specific), like `EcdsaSignature`, `ExchangeDeviceTxId` or `ExchangePayload`.

Also, some types are actually not used anywhere today (like `ApplicationDetails` or `DeviceInfo`).

Some types are also Ledger Live specific like `RawSignedTransaction`.

It feels like all these types should be either removed from the spec or reworked (like `RawSignedTransaction` that seems quite useless as a type since the object it represents is juste passed through the Client SDK from `signTransaction` to `broadcastSignedTransaction`.

Same general feeling regarding types, some types are JS specific (like `BigNumber` or `Buffer`). We should represent them in a language agnostic way (how? what type should we use?)

What do you think? What's your opinion? How should we go about that?

### CODE REVIEW

**Review by Justkant — APPROVED** [review]
Nice j'ai pas fait le tour de chaque type mais ça à l'air clean comme ça, on devra aussi update la spec rpc avec des liens vers le bon type

**Review by sprohaszka-ledger — APPROVED** [review]
I wonder if we should not explain what is a `raw` type and its purpose, unless it's common sense for everyone.

**Comment by chabroA** [comment]
> I wonder if we should not explain what is a `raw` type and its purpose, unless it's common sense for everyone.

Good idea 👍

**Comment by chabroA** [comment]
Added note regarding raw types ed4ba342649d3656408fcd4bdb0a93a4a7d61da5

For now I limited it to JSON primitive types (Strings, Numbers, Booleans, and Null) but there might not be any technical limitation to use structured types (Objects and Arrays).

With that said, if we can use Objects, then raw types might not be useful since everything can be represented by an Object 🤔

**Comment by chabroA** [comment]
recreated here https://github.com/LedgerHQ/platform-sdk/pull/7

**Pull request closed without merging**
